import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  generateTypes,
  inferJsonType,
  printValue,
  quote,
  type TypegenFlag,
} from '../src/typegen.js'
import { cleanupTempDirs, makeTempDir } from './helpers.js'

cleanupTempDirs()

const TIMESTAMP = '2026-01-02T03:04:05.000Z'
const gen = (flags: TypegenFlag[], options: Partial<Parameters<typeof generateTypes>[1]> = {}) =>
  generateTypes(flags, { project: 'acme', timestamp: TIMESTAMP, ...options })

const flag = (partial: Partial<TypegenFlag> & Pick<TypegenFlag, 'key' | 'type'>): TypegenFlag => ({
  name: partial.key,
  description: null,
  archived: false,
  variants: [],
  ...partial,
})

const boolFlag = (key: string, extra: Partial<TypegenFlag> = {}) =>
  flag({
    key,
    type: 'boolean',
    variants: [
      { key: 'on', value: true },
      { key: 'off', value: false },
    ],
    ...extra,
  })

describe('generateTypes: overall shape', () => {
  it('produces the documented module', () => {
    const output = gen([
      flag({
        key: 'pricing.plan-banner',
        name: 'Pricing page banner',
        type: 'string',
        variants: [
          { key: 'none', value: 'none' },
          { key: 'annual-discount', value: 'Save 20% with annual billing' },
          { key: 'black-friday', value: 'Black Friday' },
        ],
      }),
      boolFlag('checkout.new-payment-flow', {
        name: 'New payment flow',
        description: 'Replaces the legacy checkout.',
      }),
    ])
    expect(output).toBe(`// Generated by @modlogtv/halyard-cli — do not edit by hand.
// Project: acme · 2 flags · ${TIMESTAMP}

/** All flag keys of the project. */
export const flagKeys = ['checkout.new-payment-flow', 'pricing.plan-banner'] as const

export type FlagKey = (typeof flagKeys)[number]

/** The value type of every flag. String and number flags are unions of their variant values. */
export interface Flags {
  /** New payment flow — Replaces the legacy checkout. */
  'checkout.new-payment-flow': boolean
  /** Pricing page banner */
  'pricing.plan-banner': 'none' | 'Save 20% with annual billing' | 'Black Friday'
}

export type FlagValue<K extends FlagKey> = Flags[K]

/** Variant keys per flag. */
export interface FlagVariants {
  'checkout.new-payment-flow': 'on' | 'off'
  'pricing.plan-banner': 'none' | 'annual-discount' | 'black-friday'
}

/** Code defaults: the value of each flag's first variant. Override as needed. */
export const flagDefaults: { [K in FlagKey]: Flags[K] } = {
  'checkout.new-payment-flow': true,
  'pricing.plan-banner': 'none',
}

/** Typed wrapper for an OpenFeature client. */
export interface TypedFlagClient {
  getBooleanValue<K extends BooleanFlagKey>(key: K, defaultValue: Flags[K], context?: unknown): Promise<Flags[K]>
  getStringValue<K extends StringFlagKey>(key: K, defaultValue: Flags[K], context?: unknown): Promise<Flags[K]>
  getNumberValue<K extends NumberFlagKey>(key: K, defaultValue: Flags[K], context?: unknown): Promise<Flags[K]>
  getObjectValue<K extends JsonFlagKey>(key: K, defaultValue: Flags[K], context?: unknown): Promise<Flags[K]>
}

/** Keys of boolean flags. */
export type BooleanFlagKey = 'checkout.new-payment-flow'

/** Keys of string flags. */
export type StringFlagKey = 'pricing.plan-banner'

/** Keys of number flags. */
export type NumberFlagKey = never

/** Keys of JSON flags. */
export type JsonFlagKey = never
`)
  })

  it('is deterministic and independent of the input order', () => {
    const a = boolFlag('a.flag')
    const b = boolFlag('b.flag')
    const c = flag({ key: 'c', type: 'number', variants: [{ key: 'x', value: 1 }] })
    expect(gen([a, b, c])).toBe(gen([c, b, a]))
    expect(gen([a, b, c])).toBe(gen([a, b, c]))
  })

  it('does not mutate its input', () => {
    const flags = [boolFlag('b'), boolFlag('a')]
    gen(flags)
    expect(flags.map((f) => f.key)).toEqual(['b', 'a'])
  })

  it('uses the current time when no timestamp is given', () => {
    const before = Date.now()
    const output = generateTypes([], { project: 'acme' })
    const match = output.match(/ · (\d{4}-\d\d-\d\dT[\d:.]+Z)\n/)
    expect(match).not.toBeNull()
    expect(Date.parse(match?.[1] as string)).toBeGreaterThanOrEqual(before)
  })

  it('pluralises the flag count', () => {
    expect(gen([boolFlag('a')])).toContain('· 1 flag ·')
    expect(gen([boolFlag('a'), boolFlag('b')])).toContain('· 2 flags ·')
    expect(gen([])).toContain('· 0 flags ·')
  })

  it('wraps long key lists over several lines', () => {
    const flags = Array.from({ length: 12 }, (_, i) => boolFlag(`some.long.flag.name.${i}`))
    const output = gen(flags)
    expect(output).toContain("export const flagKeys = [\n  'some.long.flag.name.0',")
    expect(output).toContain("  'some.long.flag.name.9',\n] as const")
    expect(output).toContain('export type BooleanFlagKey =\n  | ')
  })
})

describe('generateTypes: flag types', () => {
  it('maps boolean flags to boolean regardless of the variants', () => {
    const output = gen([
      flag({ key: 'b', type: 'boolean', variants: [{ key: 'on', value: true }] }),
    ])
    expect(output).toContain('  b: boolean\n')
  })

  it('maps string flags to a union of their values, deduplicated in variant order', () => {
    const output = gen([
      flag({
        key: 's',
        type: 'string',
        variants: [
          { key: 'z', value: 'zeta' },
          { key: 'a', value: 'alpha' },
          { key: 'z2', value: 'zeta' },
        ],
      }),
    ])
    expect(output).toContain("  s: 'zeta' | 'alpha'\n")
    expect(output).toContain("  s: 'z' | 'a' | 'z2'\n")
  })

  it('escapes quotes, backslashes and newlines in string values', () => {
    const output = gen([
      flag({ key: 's', type: 'string', variants: [{ key: 'q', value: "it's a \\ \n test" }] }),
    ])
    expect(output).toContain("  s: 'it\\'s a \\\\ \\n test'\n")
  })

  it('maps number flags to a union of numeric literals', () => {
    const output = gen([
      flag({
        key: 'search.results-per-page',
        type: 'number',
        variants: [
          { key: 'a', value: 10 },
          { key: 'b', value: 25 },
          { key: 'c', value: 50 },
          { key: 'd', value: 25 },
          { key: 'e', value: -1.5 },
        ],
      }),
    ])
    expect(output).toContain("  'search.results-per-page': 10 | 25 | 50 | -1.5\n")
    expect(output).toContain("  'search.results-per-page': 10,\n")
  })

  it('widens string and number flags without variants', () => {
    const output = gen([
      flag({ key: 's', type: 'string' }),
      flag({ key: 'n', type: 'number' }),
      flag({ key: 'j', type: 'json' }),
      flag({ key: 'b', type: 'boolean' }),
    ])
    expect(output).toContain('  s: string\n')
    expect(output).toContain('  n: number\n')
    expect(output).toContain('  j: unknown\n')
    expect(output).toContain('  b: boolean\n')
    expect(output).toContain("  s: '',\n")
    expect(output).toContain('  n: 0,\n')
    expect(output).toContain('  j: null,\n')
    expect(output).toContain('  b: false,\n')
    expect(output).toContain('  j: never\n')
  })

  it('infers json flags from the union of their variants, deduplicated by printed type', () => {
    const output = gen([
      flag({
        key: 'editor.toolbar-config',
        type: 'json',
        variants: [
          { key: 'single', value: { layout: 'single-row', items: ['bold', 'italic'] } },
          { key: 'floating', value: { layout: 'floating', items: [] } },
          { key: 'other', value: { layout: 'single-row', items: ['x'] } },
          { key: 'off', value: null },
        ],
      }),
    ])
    expect(output).toContain(
      "  'editor.toolbar-config': { items: string[]; layout: string } | { items: unknown[]; layout: string } | null\n",
    )
  })

  it('defaults to the first variant value', () => {
    const output = gen([
      flag({
        key: 'j',
        type: 'json',
        variants: [{ key: 'a', value: { 'x-y': [1, 'two', null], z: {} } }],
      }),
    ])
    expect(output).toContain("  j: { 'x-y': [1, 'two', null], z: {} },\n")
  })

  it('falls back to a type default when the first variant has the wrong type', () => {
    const output = gen([
      flag({ key: 's', type: 'string', variants: [{ key: 'a', value: 5 }] }),
      flag({ key: 'n', type: 'number', variants: [{ key: 'a', value: 'x' }] }),
      flag({ key: 'b', type: 'boolean', variants: [{ key: 'a', value: 'x' }] }),
    ])
    expect(output).toContain('  s: string\n')
    expect(output).toContain("  s: '',\n")
    expect(output).toContain('  n: number\n')
    expect(output).toContain('  n: 0,\n')
    expect(output).toContain('  b: false,\n')
  })

  it('lists flag keys per type for the typed client', () => {
    const output = gen([
      boolFlag('b2'),
      boolFlag('b1'),
      flag({ key: 's', type: 'string', variants: [{ key: 'a', value: 'a' }] }),
      flag({ key: 'n', type: 'number', variants: [{ key: 'a', value: 1 }] }),
      flag({ key: 'j', type: 'json', variants: [{ key: 'a', value: {} }] }),
    ])
    expect(output).toContain("export type BooleanFlagKey = 'b1' | 'b2'\n")
    expect(output).toContain("export type StringFlagKey = 's'\n")
    expect(output).toContain("export type NumberFlagKey = 'n'\n")
    expect(output).toContain("export type JsonFlagKey = 'j'\n")
  })
})

describe('generateTypes: json inference', () => {
  it('widens primitives and keeps null', () => {
    expect(inferJsonType('x')).toBe('string')
    expect(inferJsonType(1)).toBe('number')
    expect(inferJsonType(false)).toBe('boolean')
    expect(inferJsonType(null)).toBe('null')
  })

  it('infers arrays from the union of their elements', () => {
    expect(inferJsonType([])).toBe('unknown[]')
    expect(inferJsonType(['a', 'b'])).toBe('string[]')
    expect(inferJsonType([1, 'a', 2, null])).toBe('(number | string | null)[]')
    expect(inferJsonType([[1], [2, 3]])).toBe('number[][]')
    expect(inferJsonType([{ a: 1 }, { a: 2 }])).toBe('{ a: number }[]')
    expect(inferJsonType([[], [1]])).toBe('(unknown[] | number[])[]')
  })

  it('infers nested objects with sorted keys and quotes odd keys', () => {
    expect(inferJsonType({ b: 1, a: { c: [true], 'needs-quote': null } })).toBe(
      "{ a: { c: boolean[]; 'needs-quote': null }; b: number }",
    )
    expect(inferJsonType({})).toBe('Record<string, never>')
    expect(inferJsonType({ '': 1, '1a': 2, ok_$: 3 })).toBe(
      "{ '': number; '1a': number; ok_$: number }",
    )
  })

  it('prints values as TypeScript expressions', () => {
    expect(printValue({ b: [1, 'x'], a: null })).toBe("{ a: null, b: [1, 'x'] }")
    expect(printValue("it's")).toBe("'it\\'s'")
    expect(printValue([])).toBe('[]')
  })
})

describe('generateTypes: keys and comments', () => {
  it('quotes keys that are not valid identifiers and leaves identifiers bare', () => {
    const output = gen([
      boolFlag('darkMode'),
      boolFlag('dark-mode'),
      boolFlag('1st'),
      boolFlag("it's"),
    ])
    expect(output).toContain('  darkMode: boolean\n')
    expect(output).toContain("  'dark-mode': boolean\n")
    expect(output).toContain("  '1st': boolean\n")
    expect(output).toContain("  'it\\'s': boolean\n")
    // flagKeys always quotes.
    expect(output).toContain("'darkMode'")
  })

  it('writes name and description as a doc comment and escapes comment terminators', () => {
    const output = gen([
      boolFlag('a', { name: 'Name */ evil', description: 'Line one\nline two */ x' }),
      boolFlag('b', { name: 'Only a name', description: null }),
      boolFlag('c', { name: '', description: 'Only a description' }),
      boolFlag('d', { name: '', description: null }),
    ])
    expect(output).toContain('  /** Name *\\/ evil — Line one line two *\\/ x */\n  a: boolean')
    expect(output).toContain('  /** Only a name */\n  b: boolean')
    expect(output).toContain('  /** Only a description */\n  c: boolean')
    expect(output).toContain('Flags {\n  /** Name')
    expect(output).toMatch(/\n {2}d: boolean/)
    expect(output).not.toMatch(/\/\*\* {2}\*\//)
    const comments = output.split('\n').filter((line) => line.trim().startsWith('/** Name'))
    expect(comments).toHaveLength(1)
  })
})

describe('generateTypes: options', () => {
  const flags = [boolFlag('live'), boolFlag('old', { archived: true })]

  it('excludes archived flags by default', () => {
    const output = gen(flags)
    expect(output).toContain("flagKeys = ['live'] as const")
    expect(output).not.toContain('old')
    expect(output).toContain('· 1 flag ·')
  })

  it('includes archived flags on request', () => {
    const output = gen(flags, { includeArchived: true })
    expect(output).toContain("flagKeys = ['live', 'old'] as const")
    expect(output).toContain('· 2 flags ·')
  })

  it('handles an empty project', () => {
    const output = gen([])
    expect(output).toContain('export const flagKeys = [] as const')
    expect(output).toContain('export interface Flags {}')
    expect(output).toContain('export interface FlagVariants {}')
    expect(output).toContain('flagDefaults: { [K in FlagKey]: Flags[K] } = {}')
    expect(output).toContain('export type BooleanFlagKey = never')
    expect(output).toContain('export type JsonFlagKey = never')
  })

  it('wraps the module in a namespace', () => {
    const output = gen(flags, { namespace: 'Halyard' })
    const lines = output.split('\n')
    expect(lines[0]).toBe('// Generated by @modlogtv/halyard-cli — do not edit by hand.')
    expect(lines[3]).toBe('export namespace Halyard {')
    expect(output).toContain("\n  export const flagKeys = ['live'] as const\n")
    expect(output).toContain('\n  export interface TypedFlagClient {\n')
    expect(output.endsWith('}\n')).toBe(true)
    expect(output).not.toMatch(/ +\n/)
  })

  it('accepts dotted namespaces and rejects invalid ones', () => {
    expect(gen([], { namespace: 'Acme.Flags' })).toContain('export namespace Acme.Flags {')
    expect(() => gen([], { namespace: 'not valid' })).toThrow(/Invalid namespace/)
    expect(() => gen([], { namespace: '1abc' })).toThrow(/Invalid namespace/)
    expect(() => gen([], { namespace: '} evil {' })).toThrow(/Invalid namespace/)
  })

  it('quotes safely', () => {
    expect(quote('a b')).toBe("'a\\u2028b'")
    expect(quote('\u0001')).toBe("'\\u0001'")
  })
})

describe('generated output compiles', () => {
  const fixture: TypegenFlag[] = [
    boolFlag('checkout.new-payment-flow', { name: 'New payment', description: 'Uses */ comments' }),
    flag({
      key: 'pricing.plan-banner',
      type: 'string',
      variants: [
        { key: 'none', value: 'none' },
        { key: 'annual-discount', value: "Save 20% with 'annual' billing" },
      ],
    }),
    flag({
      key: 'search.results-per-page',
      type: 'number',
      variants: [
        { key: 'a', value: 10 },
        { key: 'b', value: 25 },
        { key: 'c', value: -1 },
      ],
    }),
    flag({
      key: 'editor.toolbar-config',
      type: 'json',
      variants: [
        {
          key: 'single',
          value: { layout: 'single-row', items: ['bold'], nested: [{ a: 1 }, { a: null }] },
        },
        { key: 'floating', value: { layout: 'floating', items: [], nested: [] } },
        { key: 'none', value: null },
      ],
    }),
    flag({ key: 'empty-json', type: 'json' }),
    flag({ key: 'empty-string', type: 'string' }),
    boolFlag('camelCase'),
    boolFlag('weird "key" \\ \n'),
    boolFlag('archived-one', { archived: true }),
  ]

  const usage = `
import {
  type BooleanFlagKey,
  type FlagKey,
  type FlagValue,
  type FlagVariants,
  type Flags,
  type JsonFlagKey,
  type NumberFlagKey,
  type StringFlagKey,
  type TypedFlagClient,
  flagDefaults,
  flagKeys,
} from './flags'

declare const client: TypedFlagClient

export const keys: readonly FlagKey[] = flagKeys
export const a: FlagValue<'pricing.plan-banner'> = 'none'
export const b: Flags['search.results-per-page'] = 25
export const c: FlagVariants['pricing.plan-banner'] = 'annual-discount'
export const d: BooleanFlagKey = 'camelCase'
export const e: StringFlagKey = 'empty-string'
export const f: NumberFlagKey = 'search.results-per-page'
export const g: JsonFlagKey = 'empty-json'
export const defaults = flagDefaults['editor.toolbar-config']
export const toolbar = client.getObjectValue('editor.toolbar-config', null)
export const flagEnabled = client.getBooleanValue('camelCase', true)
export const perPage = client.getNumberValue('search.results-per-page', 10)
export const banner = client.getStringValue('pricing.plan-banner', 'none')

// @ts-expect-error not a flag key
export const bad1: FlagKey = 'does-not-exist'
// @ts-expect-error not one of the variant values
export const bad2: Flags['pricing.plan-banner'] = 'something else'
// @ts-expect-error archived flags are excluded
export const bad3: FlagKey = 'archived-one'
// @ts-expect-error a number flag is not a boolean flag
export const bad4 = client.getBooleanValue('search.results-per-page', 10)
// @ts-expect-error default must be a variant value
export const bad5 = client.getNumberValue('search.results-per-page', 11)
`

  // TypeScript 7 no longer ships the JavaScript compiler API, so the generated
  // code is type-checked by running the tsc binary on a temporary project.
  const tscBin = join(
    dirname(createRequire(import.meta.url).resolve('typescript/package.json')),
    'bin/tsc',
  )

  function compile(files: Record<string, string>): string[] {
    const dir = makeTempDir('halyard-typegen-')
    mkdirSync(dir, { recursive: true })
    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(dir, name), content)
    }
    writeFileSync(
      join(dir, 'tsconfig.json'),
      JSON.stringify({
        compilerOptions: {
          strict: true,
          noUncheckedIndexedAccess: true,
          isolatedModules: true,
          noEmit: true,
          target: 'ES2022',
          lib: ['ES2022'],
          module: 'ESNext',
          moduleResolution: 'bundler',
          types: [],
          skipLibCheck: true,
        },
        include: Object.keys(files),
      }),
    )
    const result = spawnSync(process.execPath, [tscBin, '-p', dir, '--pretty', 'false'], {
      encoding: 'utf8',
    })
    if (result.error) throw result.error
    return `${result.stdout}${result.stderr}`
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
  }

  it('type-checks with strict TypeScript and rejects wrong usage', () => {
    const diagnostics = compile({
      'flags.ts': gen(fixture),
      'usage.ts': usage,
    })
    expect(diagnostics).toEqual([])
  })

  it('type-checks an empty project', () => {
    expect(compile({ 'flags.ts': gen([]) })).toEqual([])
  })

  it('type-checks with a namespace', () => {
    const diagnostics = compile({
      'flags.ts': gen(fixture, { namespace: 'Halyard' }),
      'usage.ts': `
import { Halyard } from './flags'
export const key: Halyard.FlagKey = 'camelCase'
export const value: Halyard.Flags['search.results-per-page'] = 10
// @ts-expect-error unknown key
export const bad: Halyard.FlagKey = 'nope'
`,
    })
    expect(diagnostics).toEqual([])
  })
})
